// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nTier.Repositories.EFCore.Repositories;

#nullable disable

namespace nTier.WebApi.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20250922003015_startPoint")]
    partial class startPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nTier.Entites.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 74m,
                            Title = "Birinci Kitap"
                        },
                        new
                        {
                            Id = 2,
                            Price = 78m,
                            Title = "BirMasalKitap"
                        },
                        new
                        {
                            Id = 3,
                            Price = 56m,
                            Title = "SEnBEnsin Kitap"
                        },
                        new
                        {
                            Id = 4,
                            Price = 10m,
                            Title = "KEndin Ol Kitap"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
